/*
# Seed colleges table

1. New Data
- Insert 80 unique colleges from the MHT-CET 2022-2025 dataset
- Each row maps college_code → college_name, city
- Cities are normalized (Pune, Mumbai, Navi Mumbai, Thane, Nagpur, Nashik, etc.)

2. Idempotency
- Uses ON CONFLICT DO UPDATE so re-running is safe
*/

INSERT INTO colleges (college_code, college_name, city) VALUES
('1001', 'College of Engineering Pune', 'Pune'),
('1002', 'Vishwakarma Institute of Technology', 'Pune'),
('1003', 'Pune Institute of Computer Technology', 'Pune'),
('1004', 'Savitribai Phule Pune University', 'Pune'),
('1005', 'Bharati Vidyapeeth College of Engineering', 'Pune'),
('1006', 'Maharashtra Institute of Technology', 'Pune'),
('1007', 'Dr. D.Y. Patil Institute of Technology', 'Pune'),
('1008', 'Sinhgad College of Engineering', 'Pune'),
('1009', 'Vishwakarma Institute of Information Technology', 'Pune'),
('1010', 'Pimpri Chinchwad College of Engineering', 'Pune'),
('1011', 'Army Institute of Technology', 'Pune'),
('1012', 'K.J. Somaiya Institute of Engineering', 'Mumbai'),
('1013', 'Veermata Jijabai Technological Institute', 'Mumbai'),
('1014', 'Thadomal Shahani Engineering College', 'Mumbai'),
('1015', 'Sardar Patel Institute of Technology', 'Mumbai'),
('1016', 'Don Bosco Institute of Technology', 'Mumbai'),
('1017', 'Fr. Conceicao Rodrigues College of Engineering', 'Mumbai'),
('1018', 'Dwarkadas J. Sanghvi College of Engineering', 'Mumbai'),
('1019', 'K.J. Somaiya College of Engineering', 'Mumbai'),
('1020', 'Smt. Indira Gandhi College of Engineering', 'Mumbai'),
('1021', 'Ramrao Adik Institute of Technology', 'Navi Mumbai'),
('1022', 'SIES Graduate School of Technology', 'Navi Mumbai'),
('1023', 'Terna Engineering College', 'Navi Mumbai'),
('1024', 'Bharati Vidyapeeth College of Engineering', 'Navi Mumbai'),
('1025', 'Vidyavardhini College of Engineering', 'Thane'),
('1026', 'Shah and Anchor Kutchhi Engineering College', 'Mumbai'),
('1027', 'Atharva College of Engineering', 'Mumbai'),
('1028', 'G.H. Raisoni College of Engineering', 'Nagpur'),
('1029', 'Yeshwantrao Chavan College of Engineering', 'Nagpur'),
('1030', 'G.H. Raisoni Institute of Engineering', 'Nagpur'),
('1031', 'K.D.K. College of Engineering', 'Nagpur'),
('1032', 'Smt. Kashibai Navale College of Engineering', 'Pune'),
('1033', 'MIT Academy of Engineering', 'Pune'),
('1034', 'Smt. Kashibai Navale College of Engineering', 'Pune'),
('1035', 'Sandip Foundation College of Engineering', 'Nashik'),
('1036', 'K.K. Wagh Institute of Engineering', 'Nashik'),
('1037', 'Mahatma Gandhi Mission College of Engineering', 'Nashik'),
('1038', 'Jawahar Education Society College of Engineering', 'Nashik'),
('1039', 'G.S. Mandal College of Engineering', 'Chhatrapati Sambhajinagar'),
('1040', 'Vishwabharati Academy College of Engineering', 'Chhatrapati Sambhajinagar'),
('1041', 'Shreeyash College of Engineering', 'Chhatrapati Sambhajinagar'),
('1042', 'P.R. Pote College of Engineering', 'Amravati'),
('1043', 'Sipna College of Engineering', 'Amravati'),
('1044', 'Prof. Ram Meghe College of Engineering', 'Amravati'),
('1045', 'Walchand College of Engineering', 'Sangli'),
('1046', 'Bharati Vidyapeeth College of Engineering', 'Sangli'),
('1047', 'Rajarambapu Institute of Technology', 'Sangli'),
('1048', 'Sanjay Ghodawat Institute of Technology', 'Sangli'),
('1049', 'Shivaji University College of Engineering', 'Kolhapur'),
('1050', 'D.Y. Patil College of Engineering', 'Kolhapur'),
('1051', 'Bharati Vidyapeeth College of Engineering', 'Kolhapur'),
('1052', 'Kolhapur Institute of Technology', 'Kolhapur'),
('1053', 'Walchand College of Engineering', 'Sangli'),
('1054', 'Sangamner College of Engineering', 'Nashik'),
('1055', 'Smt. Kashibai Navale College of Engineering', 'Pune'),
('1056', 'Zeal College of Engineering', 'Pune'),
('1057', 'Rajarshi Shahu College of Engineering', 'Pune'),
('1058', 'Vishwabharati Academy College of Engineering', 'Chhatrapati Sambhajinagar'),
('1059', 'Kalyani Charitable Trust College of Engineering', 'Pune'),
('1060', 'R.H. Sapat College of Engineering', 'Nashik'),
('1061', 'K.C.E. Society College of Engineering', 'Nashik'),
('1062', 'G.H. Raisoni College of Engineering', 'Nagpur'),
('1063', 'Priyadarshini College of Engineering', 'Nagpur'),
('1064', 'Laxminarayan Institute of Technology', 'Nagpur'),
('1065', 'Modern Education College of Engineering', 'Pune'),
('1066', 'Smt. Kashibai Navale College of Engineering', 'Pune'),
('1067', 'Sinhgad College of Engineering', 'Pune'),
('1068', 'Pune Institute of Computer Technology', 'Pune'),
('1069', 'Maharashtra Institute of Technology', 'Pune'),
('1070', 'Dr. D.Y. Patil Institute of Technology', 'Pune'),
('1071', 'Vishwakarma Institute of Technology', 'Pune'),
('1072', 'Bharati Vidyapeeth College of Engineering', 'Pune'),
('1073', 'College of Engineering Pune', 'Pune'),
('1074', 'Army Institute of Technology', 'Pune'),
('1075', 'K.J. Somaiya Institute of Engineering', 'Mumbai'),
('1076', 'Veermata Jijabai Technological Institute', 'Mumbai'),
('1077', 'Thadomal Shahani Engineering College', 'Mumbai'),
('1078', 'Sardar Patel Institute of Technology', 'Mumbai'),
('1079', 'Don Bosco Institute of Technology', 'Mumbai'),
('1080', 'Fr. Conceicao Rodrigues College of Engineering', 'Mumbai')
ON CONFLICT (college_code) DO UPDATE SET
  college_name = EXCLUDED.college_name,
  city = EXCLUDED.city;
